"""
VitalSync — model routes: the Model Validation and Model Explainability pages.

Every figure served here is read from artifacts written by ``model/train.py`` at
training time.  Nothing is hardcoded and nothing is aspirational: if the cohort
changes, these numbers change with it.
"""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, HTTPException, Query

from backend.routes.deps import get_record, require_predictor, resolve_index, safe_predictor
from backend.services import feature_engineering as fe
from backend.settings import ARTIFACT_DIR, DATASET_DIR, settings

router = APIRouter(prefix="/model", tags=["model"])


def _artifact(name: str) -> Dict[str, Any]:
    path = ARTIFACT_DIR / name
    if not path.exists():
        raise HTTPException(
            status_code=503,
            detail={"error": "artifact_missing", "artifact": name, "hint": "Run: python model/train.py"},
        )
    try:
        return json.loads(path.read_text())
    except json.JSONDecodeError as exc:
        raise HTTPException(status_code=500, detail={"error": "artifact_invalid", "artifact": name, "message": str(exc)})


@router.get("/info")
def model_info() -> Dict[str, Any]:
    """The model card: what it predicts, how it was built, what it must not be used for."""
    predictor = require_predictor()
    info = predictor.info()
    info["risk_bands"] = [
        {"key": key, "label": label.upper(), "range": value}
        for (key, value), label in zip(settings.risk_bands.items(), ("low", "moderate", "high"))
    ]
    info["event_definition_display"] = (
        f"Glucose ≥ {int(settings.glucose_high_threshold_mgdl)} mg/dL sustained for at least 10 minutes within the "
        f"next {settings.forecast_horizon_minutes} minutes, and at least "
        f"{int(settings.glucose_rise_delta_mgdl)} mg/dL above the current reading."
    )
    info["explanation_methods"] = {
        "local": "TreeSHAP exact additive attributions for the fitted tree ensemble (occlusion fallback for other estimators)",
        "global": "Permutation importance measured as ROC-AUC drop on held-out patients (6 repeats)",
        "transparent_baseline": "Standardised logistic-regression coefficients with odds ratios",
    }
    info["safety"] = {
        "disclaimer": settings.disclaimer,
        "not_a_medical_device": True,
        "synthetic_data_only": True,
        "llm_in_prediction_path": False,
        "llm_role": "Natural-language phrasing of model output only",
    }
    return info


@router.get("/metrics")
def model_metrics(split: Optional[str] = Query(None, description="train | validation | test")) -> Dict[str, Any]:
    metrics = _artifact("metrics.json")
    predictor = safe_predictor()
    manifest = _artifact("train_manifest.json") if (ARTIFACT_DIR / "train_manifest.json").exists() else {}
    payload: Dict[str, Any] = {
        "model_id": predictor.model_id if predictor else manifest.get("model_id"),
        "estimator": predictor.estimator_name if predictor else manifest.get("estimator"),
        "secondary_estimator": manifest.get("secondary_estimator"),
        "dataset_kind": "Synthetic validation dataset",
        "dataset_label": "Synthetic validation dataset — generated by this repository, not clinical data",
        "splits": metrics,
        "split_strategy": manifest.get("split", {}),
        "threshold": manifest.get("threshold"),
        "threshold_selection": manifest.get("threshold_selection", {}),
        "model_selection": manifest.get("model_selection", metrics.get("candidate_selection", {})),
        "lead_time": metrics.get("lead_time", {}),
        "generated_at": manifest.get("trained_at"),
        "disclaimer": settings.disclaimer,
        "interpretation_guide": {
            "auroc": "Probability that a randomly chosen pre-event instant is scored higher than a randomly chosen non-event instant.",
            "auprc": "Area under the precision-recall curve — the more informative figure at a ~13% event prevalence.",
            "precision": "Of the instants flagged, how many were followed by a significant elevation.",
            "recall": "Of the instants followed by a significant elevation, how many were flagged.",
            "brier_score": "Mean squared error of the predicted probability (0 = perfect).",
            "ece": "Average absolute gap between predicted risk and observed event frequency across probability deciles.",
        },
        "honesty_note": (
            "These metrics are computed on signals produced by this repository's own physiological simulator, whose "
            "meal, activity and sleep inputs are also the model's features. They therefore represent an upper bound "
            "on achievable performance in this synthetic world and are not an estimate of clinical performance."
        ),
    }
    if split:
        valid = ("train", "validation", "test")
        if split not in valid or split not in payload["splits"]:
            raise HTTPException(status_code=400, detail={"error": "unknown_split", "requested": split, "available": list(valid)})
        payload["focus"] = {"split": split, "metrics": payload["splits"][split]}
    return payload


@router.get("/calibration")
def model_calibration() -> Dict[str, Any]:
    calibration = _artifact("calibration.json")
    metrics = _artifact("metrics.json")
    test = metrics.get("test", {})
    return {
        "calibration": calibration,
        "test_curve": (test.get("calibration") or {}).get("curve"),
        "reliability_by_risk_band": _reliability_by_band(),
        "reading_note": (
            "A perfectly calibrated model lies on the diagonal: when it says 70%, events occur in 70% of such "
            "instants. Calibration matters more than discrimination for a clinical alert, because the number is "
            "shown to a physician."
        ),
        "disclaimer": settings.disclaimer,
    }


def _reliability_by_band() -> List[Dict[str, Any]]:
    """Observed event rate per predicted-risk band (from the training artifacts)."""
    path = ARTIFACT_DIR / "conditional_trajectory.json"
    if not path.exists():
        return []
    data = json.loads(path.read_text())
    rows: List[Dict[str, Any]] = []
    for entry in data.get("bins", []):
        if not entry.get("sufficient"):
            continue
        rows.append(
            {
                "risk_range": entry["risk_range"],
                "mean_predicted": entry.get("mean_predicted_risk"),
                "observed_event_rate": entry.get("observed_event_rate"),
                "n_samples": entry.get("n_samples"),
            }
        )
    return rows


@router.get("/importance")
def model_importance(limit: int = Query(30, ge=1, le=90)) -> Dict[str, Any]:
    predictor = require_predictor()
    importance = _artifact("feature_importance.json")
    grouped: Dict[str, float] = {}
    for row in importance.get("primary", []):
        spec = fe.spec_for(row["feature"])
        key = spec.group if spec else "other"
        grouped[key] = grouped.get(key, 0.0) + float(row["importance_mean"])
    total = sum(abs(v) for v in grouped.values()) or 1.0
    return {
        "method": importance.get("method"),
        "primary_model": importance.get("primary_model"),
        "primary_kind": importance.get("primary_kind"),
        "n_samples_used": importance.get("n_samples_used"),
        "global": predictor.global_importance(limit),
        "by_group": [
            {
                "group": key,
                "group_label": fe.FEATURE_GROUPS.get(key, key),
                "importance": round(value, 5),
                "share": round(abs(value) / total, 4),
            }
            for key, value in sorted(grouped.items(), key=lambda item: abs(item[1]), reverse=True)
        ],
        "logistic_coefficients": predictor.logistic_coefficients(limit),
        "reading_note": (
            "Permutation importance measures how much held-out discrimination drops when a feature's values are "
            "shuffled. Unlike training-set impurity gain it is not biased toward high-cardinality features."
        ),
    }


@router.get("/features")
def model_features(group: Optional[str] = None) -> Dict[str, Any]:
    """The full feature catalogue with units and clinical meaning."""
    specs = [
        {
            "name": s.name,
            "group": s.group,
            "group_label": fe.FEATURE_GROUPS.get(s.group, s.group),
            "unit": s.unit,
            "description": s.description,
        }
        for s in fe.FEATURE_SPECS
    ]
    if group:
        specs = [s for s in specs if s["group"] == group]
    predictor = safe_predictor()
    stats = predictor.feature_stats() if predictor else {}
    for spec in specs:
        entry = stats.get(spec["name"])
        if entry:
            spec["training_distribution"] = {
                "median": round(entry["median"], 3),
                "p10": round(entry["p10"], 3),
                "p90": round(entry["p90"], 3),
                "mean": round(entry["mean"], 3),
                "std": round(entry["std"], 3),
            }
    return {
        "count": len(specs),
        "groups": [{"key": key, "label": label} for key, label in fe.FEATURE_GROUPS.items()],
        "features": specs,
        "leakage_controls": [
            "All rolling windows are right-aligned and inclusive of the current sample only.",
            "Personal baselines are estimated from an onboarding window that strictly precedes every scored sample.",
            "Future meals are never exposed; only habitual meal times learned from the past are used.",
            "Labels are built from a strictly forward-looking window (verified against a reference implementation).",
            "Splits are grouped by patient, so no patient appears in both train and test.",
        ],
    }


@router.get("/dataset")
def model_dataset() -> Dict[str, Any]:
    """Provenance for the training cohort."""
    metadata_path = DATASET_DIR / "dataset_metadata.json"
    if not metadata_path.exists():
        raise HTTPException(
            status_code=503,
            detail={"error": "dataset_metadata_missing", "hint": "Run: python datasets/synthetic/generate_cohort.py"},
        )
    metadata = json.loads(metadata_path.read_text())
    manifest = _artifact("train_manifest.json") if (ARTIFACT_DIR / "train_manifest.json").exists() else {}
    return {
        "kind": "Synthetic validation dataset",
        "metadata": metadata,
        "split": manifest.get("split", {}),
        "regeneration": {
            "command": "python datasets/synthetic/generate_cohort.py",
            "deterministic": True,
            "seed": metadata.get("cohort_seed"),
            "note": (
                "The cohort file is not committed to the repository; it is regenerated deterministically from the "
                "fixed seed in about fifteen seconds. Model artifacts, which are committed, were trained on exactly "
                "this configuration."
            ),
        },
        "contains_real_patient_data": False,
        "licence": metadata.get("licence"),
    }


@router.get("/explain")
def explain_endpoint(
    patient_id: Optional[str] = Query(None),
    at: Optional[str] = Query(None),
    index: Optional[int] = Query(None),
    session_id: Optional[str] = Query(None),
    top_k: int = Query(12, ge=1, le=40),
) -> Dict[str, Any]:
    """Local explanation for one prediction (Model Explainability page)."""
    predictor = require_predictor()
    record = get_record(patient_id or settings.demo_patient_id)
    position = resolve_index(record, index=index, at=at, session_id=session_id)
    features = record.feature_row(position)
    attribution = predictor.explain(features, top_k=top_k)
    return {
        "patient_id": record.patient_id,
        "as_of": record.timestamp_at(position).isoformat(),
        "probability": round(float(record.risk_primary[position]), 4),
        "secondary_probability": round(float(record.risk_secondary[position]), 4),
        "attribution": attribution,
        "feature_values": features,
        "global_context": {
            "top_global_features": predictor.global_importance(10),
            "note": "Local attributions explain this instant; global importance explains the model overall.",
        },
        "disclaimer": settings.disclaimer,
    }


@router.get("/limitations")
def limitations() -> Dict[str, Any]:
    """Limitations & Ethics page content — grounded in what the system actually does."""
    predictor = safe_predictor()
    metrics = _artifact("metrics.json") if (ARTIFACT_DIR / "metrics.json").exists() else {}
    test = metrics.get("test", {})
    return {
        "disclaimer": settings.disclaimer,
        "categories": [
            {
                "title": "Data",
                "items": [
                    "All patients, signals and outcomes are synthetic. No real patient data was used at any point.",
                    "The simulator is smoother and more regular than real physiology: real CGM traces contain dropouts, calibration shifts, compression artefacts and sensor noise this prototype does not model.",
                    "Reported metrics are measured on this synthetic cohort and are an upper bound, not an estimate of clinical performance.",
                ],
            },
            {
                "title": "Model",
                "items": [
                    "The model learns the simulator's own meal, activity and sleep dynamics, so its strongest features are the same ones that generate the labels. In deployment that coupling does not exist.",
                    "Meal-timing priors are learned from the patient's own logs; if logging adherence falls, the most informative feature degrades first.",
                    f"Test AUROC {test.get('auroc')} and recall {test.get('recall')} come with false positives: at the operating threshold {(test.get('confusion_matrix') or {}).get('fp')} of {(test.get('confusion_matrix') or {}).get('total')} scored instants were flagged incorrectly.",
                    "A 2-hour horizon is a compromise: shorter horizons are more accurate but leave less time to act.",
                ],
            },
            {
                "title": "Clinical use",
                "items": [
                    "Not a medical device and not validated in any clinical setting.",
                    "No treatment, dosing or diagnostic recommendation is produced or implied by this prototype.",
                    "Alert fatigue is a real risk: any deployment would need per-patient thresholds, quiet hours and escalation rules that are out of scope here.",
                    "Hypoglycaemia prediction is not covered by this model, although it is the more immediately dangerous event.",
                ],
            },
            {
                "title": "Equity & bias",
                "items": [
                    "Personal baselines require an onboarding window; patients who cannot wear a sensor continuously for 48 hours get weaker predictions.",
                    "Access to a CGM and a wearable is itself inequitable, so the benefit of such a system would not be distributed evenly.",
                    "Skin tone, perfusion and motion affect optical HR and HRV accuracy in real wearables; the synthetic generator does not model that disparity, so this prototype cannot measure it.",
                    "The synthetic cohort's demographic spread is narrow by construction and does not represent any real population.",
                ],
            },
            {
                "title": "Privacy & governance",
                "items": [
                    "Continuous glucose, sleep and location-adjacent activity data are highly sensitive; real deployment would require consent, encryption at rest, retention limits and access auditing.",
                    "The Groq API key is held server-side only and never reaches the browser.",
                    "Only structured, already-computed values are sent to the language model — never raw traces and never credentials.",
                    "A deterministic fallback means the system can run with no external network dependency at all.",
                ],
            },
            {
                "title": "Language model",
                "items": [
                    "Groq writes clinician-facing prose. It never produces a probability, a diagnosis or a threshold.",
                    "The prompt forbids inventing measurements, diagnoses, medications, symptoms, test results or events.",
                    "Outputs are schema-validated; malformed responses fall back to deterministic templates.",
                    "Generated text should always be read alongside the numbers it was built from.",
                ],
            },
        ],
        "model_in_use": {
            "model_id": predictor.model_id if predictor else None,
            "estimator": predictor.estimator_name if predictor else None,
            "trained": predictor is not None,
        },
        "what_would_be_needed_before_clinical_use": [
            "Prospective validation on real CGM and wearable data across diverse populations.",
            "Comparison against clinician judgement and against existing alarm systems.",
            "Regulatory review, clinical governance sign-off and a documented risk-management file.",
            "Human-factors testing of the alert interface with the clinicians who would use it.",
            "Post-deployment monitoring for drift, calibration decay and alert-fatigue effects.",
        ],
    }
